### ISSUE TITLE
Preparation issue

### ISSUE THREAD

**Issue by Ahmedradwancs** [Abshir112/Test_FullStack#2]
Everyone needs to study React, finalize their labs and participate in the test project with ideas and GitHub practicing.

**Comment by JwanMardini** [comment]
I'm learning it right now

**Comment by Abshir112** [comment]
Here I am

**Comment by Ahmedradwancs** [comment]
Thank you @JwanMardini  and @Abshir112  for commenting.

**Comment by Alloush95** [comment]
🙋‍♂️
